/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'inDevelopment' : IDL.Null,
  'released' : IDL.Null,
  'comingSoon' : IDL.Null,
});
export const Game = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'genre' : IDL.Text,
});

export const idlService = IDL.Service({
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'inDevelopment' : IDL.Null,
    'released' : IDL.Null,
    'comingSoon' : IDL.Null,
  });
  const Game = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'genre' : IDL.Text,
  });
  
  return IDL.Service({ 'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']) });
};

export const init = ({ IDL }) => { return []; };