/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : string,
  'status' : Status,
  'title' : string,
  'link' : [] | [string],
  'year' : bigint,
  'description' : string,
  'genre' : string,
}
export type Status = { 'inDevelopment' : null } |
  { 'released' : null } |
  { 'comingSoon' : null };
export interface _SERVICE { 'getGames' : ActorMethod<[], Array<Game>> }
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];